<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>PS4ApolloAutoBackup</AssemblyName>
    <Version>1.1.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Apollo.Core/Apollo.Core.csproj" />
    <Content Include="../../src/*.ps1" Link="Engine/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../Integration/*.ps1" Link="Integration/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../README.md" Link="README.md" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../docs/*.md" Link="docs/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../CHANGELOG.md" Link="CHANGELOG.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
